
(() => {
const DB_NAME='newtab_prefs',DB_VERSION=1,STORE='kv';
const K={bg:'bg.current',layout:'prefs.layout',appearance:'prefs.appearance',ws:'prefs.widgetSettings'};
const IDS=['quickLinks','mediaPlayback','todo','notes','calendar','pomodoro','systemStats'];
const DEF_LAYOUT={enabled:{quickLinks:false,mediaPlayback:false,todo:false,notes:false,calendar:false,pomodoro:false,systemStats:false},order:[...IDS],placementMode:'grid',positions:{}};
const DEF_APP={searchBottom:80,searchWidth:600,glassBlur:20,overlayDim:35,clockVisible:true,clock24h:false,videoMuted:true,videoPaused:false,youtubeBgEnabled:false};
const DEF_WS={quickLinks:{links:[{label:'YouTube',url:'https://www.youtube.com'},{label:'GitHub',url:'https://github.com'}]},mediaPlayback:{refreshSec:4},todo:{items:['Review sprint board']},notes:{text:''},calendar:{provider:'local'},pomodoro:{workMinutes:25,breakMinutes:5},systemStats:{showBattery:true,showRam:true,showCpu:true}};
const S={bgCurrent:null,bgObjectUrl:null,layout:structuredClone(DEF_LAYOUT),appearance:structuredClone(DEF_APP),widgetSettings:structuredClone(DEF_WS),drawerOpen:false,pomo:{remaining:0,mode:'work',timerId:null},accentTimer:null,media:{pollId:null,lastTabId:null},ytBg:{pollId:null,active:false,videoId:'',frameReady:false}};
const E={bgVideo:gid('bgVideo'),bgYt:gid('bgYoutubeFrame'),bgImage:gid('bgImage'),clock:gid('clock'),widgets:gid('widgetsContainer'),searchForm:gid('searchForm'),q:gid('q'),
settingsToggle:gid('settingsToggle'),drawer:gid('settingsDrawer'),backdrop:gid('drawerBackdrop'),close:gid('closeDrawer'),tabs:[...document.querySelectorAll('.tab-btn')],panels:[...document.querySelectorAll('.tab-panel')],
bgFile:gid('bgFileInput'),bgUrl:gid('bgUrlInput'),bgApply:gid('bgUrlApplyBtn'),bgReset:gid('bgResetBtn'),bgStatus:gid('bgStatus'),vMuted:gid('videoMutedToggle'),vPaused:gid('videoPausedToggle'),ytBgToggle:gid('youtubeBgToggle'),bgDim:gid('bgDimSlider'),bgBlur:gid('bgBlurSlider'),
widgetList:gid('widgetList'),widgetSettings:gid('widgetSettingsMount'),minimal:gid('minimalModeBtn'),placementMode:gid('widgetPlacementMode'),resetPositions:gid('resetWidgetPositionsBtn'),
searchBottom:gid('searchBottomSlider'),searchWidth:gid('searchWidthSlider'),glassBlur:gid('glassBlurSlider'),overlayDim:gid('overlayDimSlider'),clockVisible:gid('clockVisibleToggle'),clock24h:gid('clock24hToggle'),
exportBtn:gid('exportPrefsBtn'),importInput:gid('importPrefsInput'),resetAll:gid('resetAllBtn')};
function gid(id){return document.getElementById(id);} 
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
const WIDGET_W=260,WIDGET_H=170;
const ACCENT_SIZE=24;
const ACCENT_CANVAS=document.createElement('canvas');
ACCENT_CANVAS.width=ACCENT_SIZE;
ACCENT_CANVAS.height=ACCENT_SIZE;
const ACCENT_CTX=ACCENT_CANVAS.getContext('2d',{willReadFrequently:true});
const isVideoUrl=(u)=>/\.(mp4|webm)(\?.*)?$/i.test(u||'');
const blobType=(b)=>b&&typeof b.type==='string'?b.type.toLowerCase():'';
const SAFE_PROTOCOLS=new Set(['http:','https:']);
function parseSafeUrl(raw){if(typeof raw!=='string')return null;const t=raw.trim();if(!t)return null;try{const u=new URL(t);return SAFE_PROTOCOLS.has(u.protocol)?u:null;}catch(_){return null;}}
function normQuickLinks(links){if(!Array.isArray(links))return [];return links.map(v=>{if(!v||typeof v!=='object')return null;const u=parseSafeUrl(v.url);if(!u)return null;const label=(typeof v.label==='string'?v.label.trim():'').slice(0,60)||u.hostname;return{label,url:u.href};}).filter(Boolean).slice(0,20);}
function normBg(x){if(!x||typeof x!=='object')return null;if(x.type==='blob'&&x.value instanceof Blob)return{type:'blob',value:x.value};if(x.type==='url'){const u=parseSafeUrl(x.value);if(u)return{type:'url',value:u.href};}return null;}
function collectImportHosts(j){const hosts=new Set();if(!j||typeof j!=='object')return[];if(j.bgCurrent&&j.bgCurrent.type==='url'){const u=parseSafeUrl(j.bgCurrent.value);if(u)hosts.add(u.host);}if(j.widgetSettings&&j.widgetSettings.quickLinks&&Array.isArray(j.widgetSettings.quickLinks.links)){j.widgetSettings.quickLinks.links.forEach(v=>{const u=parseSafeUrl(v&&v.url);if(u)hosts.add(u.host);});}return[...hosts];}
const MEDIA_DOMAINS=new Set(['music.youtube.com','open.spotify.com','music.apple.com']);
const YT_POLL_MS=4000;
const YT_ORIGIN='https://www.youtube.com';
const YT_HTTP_CONTEXT=window.location.protocol==='http:'||window.location.protocol==='https:';
const canUseExtMedia=()=>typeof chrome!=='undefined'&&!!(chrome.tabs&&chrome.scripting);
function chromeTabsQuery(query){return new Promise((res,rej)=>{try{chrome.tabs.query(query,tabs=>{const err=chrome.runtime&&chrome.runtime.lastError;if(err)rej(new Error(err.message||'tabs.query failed'));else res(tabs||[]);});}catch(e){rej(e);}});}
function chromeExecInTab(tabId,func,args=[]){return new Promise((res,rej)=>{try{chrome.scripting.executeScript({target:{tabId},func,args},out=>{const err=chrome.runtime&&chrome.runtime.lastError;if(err)rej(new Error(err.message||'executeScript failed'));else res(out&&out[0]?out[0].result:null);});}catch(e){rej(e);}});}
function focusTab(tab){if(!canUseExtMedia()||!tab||!Number.isInteger(tab.id))return;try{chrome.tabs.update(tab.id,{active:true},()=>{});if(Number.isInteger(tab.windowId)&&chrome.windows&&chrome.windows.update)chrome.windows.update(tab.windowId,{focused:true},()=>{});}catch(_){ }}
function sourceFromUrl(url){const u=parseSafeUrl(url);if(!u)return{name:'Unknown source',logo:''};const host=u.hostname.replace(/^www\./,'');if(host==='music.youtube.com')return{name:'YouTube Music',logo:'https://music.youtube.com/favicon.ico'};if(host==='open.spotify.com')return{name:'Spotify',logo:'https://open.spotify.com/favicon.ico'};if(host==='music.apple.com')return{name:'Apple Music',logo:'https://music.apple.com/favicon.ico'};return{name:host,logo:`${u.origin}/favicon.ico`};}
async function readMediaSnapshot(tabId){return chromeExecInTab(tabId,()=>{const md=navigator.mediaSession&&navigator.mediaSession.metadata;const art=md&&Array.isArray(md.artwork)?md.artwork:[];const pick=art.length?String(art[art.length-1].src||''):'';const media=[...document.querySelectorAll('audio,video')];const hasMedia=media.length>0;const playing=media.some(m=>!m.paused&&!m.ended);const active=media.find(m=>!m.paused&&!m.ended)||media[0]||null;const fallbackArt=active&&typeof active.poster==='string'?active.poster:'';return{title:(md&&md.title)||document.title||'',artist:(md&&md.artist)||'',album:(md&&md.album)||'',artwork:pick||fallbackArt||'',hasMedia,playing};});}
async function resolveMediaState(){if(!canUseExtMedia())return null;const all=(await chromeTabsQuery({})).filter(t=>Number.isInteger(t.id)&&parseSafeUrl(t.url||''));if(!all.length)return null;const seen=new Set(),ordered=[];const push=t=>{if(!t||seen.has(t.id))return;seen.add(t.id);ordered.push(t);};push(all.find(t=>t.id===S.media.lastTabId));all.filter(t=>!!t.audible).forEach(push);all.filter(t=>{const u=parseSafeUrl(t.url||'');return u&&MEDIA_DOMAINS.has(u.hostname);}).forEach(push);all.filter(t=>!!t.active).forEach(push);all.forEach(push);for(const tab of ordered.slice(0,12)){const snap=await readMediaSnapshot(tab.id).catch(()=>null);if(!snap)continue;if(snap.playing||snap.hasMedia||(snap.title&&snap.title!==tab.title))return{tab,snap};}const fallback=ordered[0];if(!fallback)return null;const snap=await readMediaSnapshot(fallback.id).catch(()=>null);return snap?{tab:fallback,snap}:null;}
async function sendMediaControl(tabId,action){
if(!canUseExtMedia()||!Number.isInteger(tabId))return false;
return !!(await chromeExecInTab(tabId,(act)=>{
const visible=(el)=>{if(!el||!(el instanceof HTMLElement))return false;const s=getComputedStyle(el);const r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;};
const disabled=(el)=>!!(el&&el instanceof HTMLElement&&(el.matches(':disabled,[aria-disabled=\"true\"]')||el.getAttribute('tabindex')==='-1'));
const textOf=(el)=>`${el.getAttribute('aria-label')||''} ${el.getAttribute('title')||''} ${el.textContent||''}`.toLowerCase();
const clickRx=(rxList)=>{const nodes=[...document.querySelectorAll('button,[role=\"button\"],a,div[tabindex]')];for(const n of nodes){if(!visible(n)||disabled(n))continue;const t=textOf(n);if(rxList.some(rx=>rx.test(t))){n.click();return true;}}return false;};
const media=[...document.querySelectorAll('audio,video')];
const isPlaying=()=>media.some(m=>!m.paused&&!m.ended);
const pauseMedia=()=>{if(!media.length)return false;let did=false;media.forEach(m=>{if(!m.paused){m.pause();did=true;}});return did;};
const playMedia=()=>{if(!media.length)return false;let did=false;media.forEach(m=>{did=true;m.play().catch(()=>{});});return did;};
const RX_PLAY=[/\bplay\b/i,/\bresume\b/i,/\bunpause\b/i];
const RX_PAUSE=[/\bpause\b/i];
const RX_TOGGLE=[/\bplay\b[\s/\\-]*\bpause\b/i,/\bpause\b[\s/\\-]*\bplay\b/i];
if(act==='playpause'){
if(isPlaying()){
if(clickRx([...RX_PAUSE,...RX_TOGGLE]))return true;
return pauseMedia();
}
if(clickRx([...RX_PLAY,...RX_TOGGLE,...RX_PAUSE]))return true;
return playMedia();
}
if(act==='next')return clickRx([/\bnext\b/i,/\bskip\b/i,/\bforward\b/i]);
if(act==='prev')return clickRx([/\bprevious\b/i,/\bprev\b/i,/\bback\b/i,/\brewind\b/i]);
return false;
},[action]).catch(()=>false));
}
function stopMediaPolling(){if(S.media.pollId){clearInterval(S.media.pollId);S.media.pollId=null;}}
function normalizeHost(host){return String(host||'').toLowerCase().replace(/^www\./,'');}
function isYouTubeHost(host){const h=normalizeHost(host);return h==='youtu.be'||h==='youtube.com'||h.endsWith('.youtube.com');}
function cleanYouTubeVideoId(raw){const id=String(raw||'').trim();return /^[a-zA-Z0-9_-]{11}$/.test(id)?id:'';}
function extractYouTubeVideoId(rawUrl){const u=parseSafeUrl(rawUrl);if(!u||!isYouTubeHost(u.hostname))return'';const h=normalizeHost(u.hostname);if(h==='youtu.be')return cleanYouTubeVideoId(u.pathname.split('/').filter(Boolean)[0]||'');if(u.pathname==='/watch')return cleanYouTubeVideoId(u.searchParams.get('v')||'');const m=u.pathname.match(/^\/(?:shorts|embed|live)\/([^/?#]+)/i);return cleanYouTubeVideoId(m&&m[1]||'');}
function buildYouTubeEmbedUrl(videoId){const q=new URLSearchParams({autoplay:'1',mute:'1',controls:'0',modestbranding:'1',playsinline:'1',rel:'0',loop:'1',playlist:videoId,iv_load_policy:'3',disablekb:'1',vq:'hd1080'});if(YT_HTTP_CONTEXT){q.set('enablejsapi','1');q.set('origin',window.location.origin);q.set('widget_referrer',window.location.origin);}return `${YT_ORIGIN}/embed/${videoId}?${q.toString()}`;}
function isYouTubeEmbedUrl(raw){if(typeof raw!=='string')return false;return raw.startsWith(`${YT_ORIGIN}/embed/`);}
async function resolveYouTubePlayback(){if(!canUseExtMedia())return null;const all=(await chromeTabsQuery({})).filter(t=>Number.isInteger(t.id));if(!all.length)return null;const seen=new Set(),ordered=[];const push=t=>{if(!t||seen.has(t.id))return;seen.add(t.id);ordered.push(t);};all.filter(t=>!!t.audible).forEach(push);all.filter(t=>!!t.active).forEach(push);all.forEach(push);for(const tab of ordered.slice(0,16)){const videoId=extractYouTubeVideoId(tab.url||'');if(!videoId)continue;const snap=await readMediaSnapshot(tab.id).catch(()=>null);if(!snap||!snap.playing)continue;return{tab,snap,videoId};}return null;}
function postYouTubeBgCommand(func,args=[]){if(!YT_HTTP_CONTEXT||!E.bgYt||!E.bgYt.contentWindow||!S.ytBg.frameReady)return;const frameSrc=E.bgYt.getAttribute('src')||E.bgYt.src||'';if(!isYouTubeEmbedUrl(frameSrc))return;try{E.bgYt.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'*');}catch(_){ }}
function requestYouTube1080p(){postYouTubeBgCommand('mute');postYouTubeBgCommand('setPlaybackQualityRange',['hd1080']);postYouTubeBgCommand('setPlaybackQuality',['hd1080']);postYouTubeBgCommand('playVideo');}
function showYouTubeBackground(videoId){const safeId=cleanYouTubeVideoId(videoId);if(!safeId||!E.bgYt)return;const nextSrc=buildYouTubeEmbedUrl(safeId);if(E.bgYt.src!==nextSrc){S.ytBg.frameReady=false;E.bgYt.onload=()=>{S.ytBg.frameReady=true;requestYouTube1080p();setTimeout(requestYouTube1080p,350);setTimeout(requestYouTube1080p,1200);};E.bgYt.onerror=()=>{S.ytBg.frameReady=false;};E.bgYt.src=nextSrc;}else if(S.ytBg.frameReady)requestYouTube1080p();E.bgYt.style.display='block';E.bgVideo.pause();E.bgVideo.style.display='none';E.bgImage.style.display='none';S.ytBg.active=true;S.ytBg.videoId=safeId;refreshWallpaperAccent();}
function hideYouTubeBackground(){if(!E.bgYt)return;E.bgYt.onload=null;E.bgYt.onerror=null;E.bgYt.style.display='none';E.bgYt.removeAttribute('src');S.ytBg.active=false;S.ytBg.videoId='';S.ytBg.frameReady=false;refreshWallpaperAccent();}
function stopYouTubeBgPolling(){if(S.ytBg.pollId){clearInterval(S.ytBg.pollId);S.ytBg.pollId=null;}}
async function syncYouTubeBackground(){if(!S.appearance.youtubeBgEnabled){if(S.ytBg.active){hideYouTubeBackground();renderBg();}return;}if(!YT_HTTP_CONTEXT){if(S.ytBg.active){hideYouTubeBackground();renderBg();}setBgStatus('YouTube background is blocked on extension new-tab pages by YouTube Referer policy (Error 153).');return;}if(!canUseExtMedia()){if(S.ytBg.active){hideYouTubeBackground();renderBg();}setBgStatus('YouTube background needs tabs and scripting permissions.');return;}const state=await resolveYouTubePlayback().catch(()=>null);if(state&&state.videoId){if(!S.ytBg.active||S.ytBg.videoId!==state.videoId){showYouTubeBackground(state.videoId);setBgStatus('YouTube background active (requesting 1080p when available). If Error 153 appears, sign in to YouTube and reload.');}else requestYouTube1080p();return;}if(S.ytBg.active){hideYouTubeBackground();renderBg();setBgStatus('YouTube playback stopped. Restored saved background.');return;}setBgStatus('YouTube background enabled. Start a YouTube video to use it.');}
function updateYouTubeBgMode(){stopYouTubeBgPolling();if(!S.appearance.youtubeBgEnabled){const wasActive=S.ytBg.active;hideYouTubeBackground();renderBg();if(wasActive)setBgStatus('YouTube background disabled. Restored saved background.');return;}if(!YT_HTTP_CONTEXT){S.appearance.youtubeBgEnabled=false;syncAppControls();hideYouTubeBackground();renderBg();setBgStatus('YouTube background cannot run on chrome://newtab (Error 153).');saveApp().catch(()=>{});return;}syncYouTubeBackground().catch(()=>{});S.ytBg.pollId=setInterval(()=>{syncYouTubeBackground().catch(()=>{});},YT_POLL_MS);}
function normLayout(x){const o={enabled:{...DEF_LAYOUT.enabled},order:[...DEF_LAYOUT.order],placementMode:'grid',positions:{}};if(x&&typeof x==='object'){if(x.enabled&&typeof x.enabled==='object')IDS.forEach(id=>typeof x.enabled[id]==='boolean'&&(o.enabled[id]=x.enabled[id]));if(Array.isArray(x.order)){const d=[...new Set(x.order.filter(id=>IDS.includes(id)))];IDS.forEach(id=>!d.includes(id)&&d.push(id));o.order=d;}if(x.placementMode==='custom'||x.placementMode==='grid')o.placementMode=x.placementMode;if(x.positions&&typeof x.positions==='object'){IDS.forEach(id=>{const p=x.positions[id];if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))o.positions[id]={x:clamp(+p.x,0,5000),y:clamp(+p.y,0,5000)};});}}return o;}
function normApp(x){const a={...DEF_APP};if(x&&typeof x==='object'){if(Number.isFinite(x.searchBottom))a.searchBottom=clamp(+x.searchBottom,20,160);if(Number.isFinite(x.searchWidth))a.searchWidth=clamp(+x.searchWidth,360,820);if(Number.isFinite(x.glassBlur))a.glassBlur=clamp(+x.glassBlur,6,30);if(Number.isFinite(x.overlayDim))a.overlayDim=clamp(+x.overlayDim,0,70);if(typeof x.clockVisible==='boolean')a.clockVisible=x.clockVisible;if(typeof x.clock24h==='boolean')a.clock24h=x.clock24h;if(typeof x.videoMuted==='boolean')a.videoMuted=x.videoMuted;if(typeof x.videoPaused==='boolean')a.videoPaused=x.videoPaused;if(typeof x.youtubeBgEnabled==='boolean')a.youtubeBgEnabled=x.youtubeBgEnabled;}return a;}
function normWS(x){const m=structuredClone(DEF_WS);if(!x||typeof x!=='object')return m;if(x.quickLinks&&Array.isArray(x.quickLinks.links))m.quickLinks.links=normQuickLinks(x.quickLinks.links);if(x.mediaPlayback&&typeof x.mediaPlayback==='object'&&Number.isFinite(x.mediaPlayback.refreshSec))m.mediaPlayback.refreshSec=clamp(+x.mediaPlayback.refreshSec,2,15);if(x.todo&&Array.isArray(x.todo.items))m.todo.items=x.todo.items.filter(v=>typeof v==='string').slice(0,40);if(x.notes&&typeof x.notes.text==='string')m.notes.text=x.notes.text.slice(0,10000);if(x.calendar&&typeof x.calendar.provider==='string')m.calendar.provider=x.calendar.provider;if(x.pomodoro&&typeof x.pomodoro==='object'){if(Number.isFinite(x.pomodoro.workMinutes))m.pomodoro.workMinutes=clamp(+x.pomodoro.workMinutes,1,120);if(Number.isFinite(x.pomodoro.breakMinutes))m.pomodoro.breakMinutes=clamp(+x.pomodoro.breakMinutes,1,60);}if(x.systemStats&&typeof x.systemStats==='object'){if(typeof x.systemStats.showBattery==='boolean')m.systemStats.showBattery=x.systemStats.showBattery;if(typeof x.systemStats.showRam==='boolean')m.systemStats.showRam=x.systemStats.showRam;if(typeof x.systemStats.showCpu==='boolean')m.systemStats.showCpu=x.systemStats.showCpu;}return m;}
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('idb open failed'));});}
async function dbGet(k){const db=await dbOpen();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly');const r=t.objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);t.oncomplete=()=>db.close();});}
async function dbSet(k,v){const db=await dbOpen();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=()=>{db.close();res();};t.onerror=()=>rej(t.error);});}
async function dbClear(){const db=await dbOpen();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=()=>{db.close();res();};t.onerror=()=>rej(t.error);});}
function saveLayout(){return dbSet(K.layout,S.layout);}function saveApp(){return dbSet(K.appearance,S.appearance);}function saveWS(){return dbSet(K.ws,S.widgetSettings);}function saveBg(){return dbSet(K.bg,S.bgCurrent);}
function setBgStatus(t){E.bgStatus.textContent=t;}
function clearObjUrl(){if(S.bgObjectUrl){URL.revokeObjectURL(S.bgObjectUrl);S.bgObjectUrl=null;}}
function setStatAccent(c1,c2){const r=document.documentElement;r.style.setProperty('--stat-accent-1',c1);r.style.setProperty('--stat-accent-2',c2);}
function hslToRgb(h,s,l){const c=(1-Math.abs(2*l-1))*s;const x=c*(1-Math.abs((h/60)%2-1));const m=l-c/2;let rr=0,gg=0,bb=0;if(h<60){rr=c;gg=x;}else if(h<120){rr=x;gg=c;}else if(h<180){gg=c;bb=x;}else if(h<240){gg=x;bb=c;}else if(h<300){rr=x;bb=c;}else{rr=c;bb=x;}return{r:Math.round((rr+m)*255),g:Math.round((gg+m)*255),b:Math.round((bb+m)*255)};}
function rgbToHsl(r,g,b){const rn=r/255,gn=g/255,bn=b/255,max=Math.max(rn,gn,bn),min=Math.min(rn,gn,bn),d=max-min;let h=0,s=0,l=(max+min)/2;if(d!==0){s=d/(1-Math.abs(2*l-1));if(max===rn)h=60*(((gn-bn)/d)%6);else if(max===gn)h=60*((bn-rn)/d+2);else h=60*((rn-gn)/d+4);}if(h<0)h+=360;return{h,s,l};}
function sampleWallpaperAccent(){if(!ACCENT_CTX){setStatAccent('rgba(139,205,255,.85)','rgba(95,255,195,.9)');return;}let src=null;if(E.bgVideo.style.display!=='none'&&E.bgVideo.readyState>=2)src=E.bgVideo;else if(E.bgImage.style.display!=='none'&&E.bgImage.complete)src=E.bgImage;if(!src){setStatAccent('rgba(139,205,255,.85)','rgba(95,255,195,.9)');return;}try{ACCENT_CTX.clearRect(0,0,ACCENT_SIZE,ACCENT_SIZE);ACCENT_CTX.drawImage(src,0,0,ACCENT_SIZE,ACCENT_SIZE);const data=ACCENT_CTX.getImageData(0,0,ACCENT_SIZE,ACCENT_SIZE).data;let r=0,g=0,b=0,c=0;for(let i=0;i<data.length;i+=4){const a=data[i+3];if(a<12)continue;r+=data[i];g+=data[i+1];b+=data[i+2];c++;}if(!c){setStatAccent('rgba(139,205,255,.85)','rgba(95,255,195,.9)');return;}const base=rgbToHsl(r/c,g/c,b/c);const sat=clamp(base.s*1.25,0.35,0.88);const l1=clamp(base.l*0.92,0.38,0.62);const l2=clamp(base.l*1.18,0.46,0.74);const c1=hslToRgb(base.h,sat,l1);const c2=hslToRgb((base.h+42)%360,sat,l2);setStatAccent(`rgba(${c1.r},${c1.g},${c1.b},0.88)`,`rgba(${c2.r},${c2.g},${c2.b},0.94)`);}catch(_){setStatAccent('rgba(139,205,255,.85)','rgba(95,255,195,.9)');}}
function refreshWallpaperAccent(){sampleWallpaperAccent();if(S.accentTimer){clearInterval(S.accentTimer);S.accentTimer=null;}if(E.bgVideo.style.display!=='none'&&E.bgVideo.src)S.accentTimer=setInterval(sampleWallpaperAccent,2000);}
function applyAppearance(){const r=document.documentElement;r.style.setProperty('--search-bottom',String(S.appearance.searchBottom));r.style.setProperty('--search-width',String(S.appearance.searchWidth));r.style.setProperty('--glass-blur',String(S.appearance.glassBlur));r.style.setProperty('--overlay-dim',String(S.appearance.overlayDim));E.clock.style.display=S.appearance.clockVisible?'block':'none';E.bgVideo.muted=S.appearance.videoMuted;if(S.appearance.videoPaused)E.bgVideo.pause();else if(E.bgVideo.style.display!=='none'&&E.bgVideo.src)E.bgVideo.play().catch(()=>{});}
function syncAppControls(){E.searchBottom.value=String(S.appearance.searchBottom);E.searchWidth.value=String(S.appearance.searchWidth);E.glassBlur.value=String(S.appearance.glassBlur);E.overlayDim.value=String(S.appearance.overlayDim);E.clockVisible.checked=S.appearance.clockVisible;E.clock24h.checked=S.appearance.clock24h;E.bgDim.value=String(S.appearance.overlayDim);E.bgBlur.value=String(S.appearance.glassBlur);E.vMuted.checked=S.appearance.videoMuted;E.vPaused.checked=S.appearance.videoPaused;if(E.ytBgToggle)E.ytBgToggle.checked=S.appearance.youtubeBgEnabled;}
function renderBg(){const b=S.bgCurrent;const keepYtOverride=()=>{if(S.appearance.youtubeBgEnabled&&S.ytBg.active&&E.bgYt){E.bgVideo.pause();E.bgVideo.style.display='none';E.bgImage.style.display='none';E.bgYt.style.display='block';}};E.bgVideo.pause();E.bgVideo.removeAttribute('src');E.bgVideo.load();E.bgVideo.style.display='none';E.bgImage.removeAttribute('src');E.bgImage.style.display='none';if(E.bgYt&&!S.ytBg.active)E.bgYt.style.display='none';clearObjUrl();if(!b){setBgStatus('Using default dark background.');keepYtOverride();refreshWallpaperAccent();return;}if(b.type==='url'&&typeof b.value==='string'){if(isVideoUrl(b.value)){E.bgVideo.crossOrigin='anonymous';E.bgVideo.src=b.value;E.bgVideo.style.display='block';if(!S.appearance.videoPaused)E.bgVideo.play().catch(()=>{});setBgStatus('Background source: URL video.');E.bgVideo.addEventListener('loadeddata',sampleWallpaperAccent,{once:true});}else{E.bgImage.crossOrigin='anonymous';E.bgImage.src=b.value;E.bgImage.style.display='block';setBgStatus('Background source: URL image.');if(E.bgImage.complete)sampleWallpaperAccent();else E.bgImage.onload=sampleWallpaperAccent;}keepYtOverride();refreshWallpaperAccent();return;}if(b.type==='blob'&&b.value instanceof Blob){S.bgObjectUrl=URL.createObjectURL(b.value);if(blobType(b.value).startsWith('video/')){E.bgVideo.src=S.bgObjectUrl;E.bgVideo.style.display='block';if(!S.appearance.videoPaused)E.bgVideo.play().catch(()=>{});setBgStatus('Background source: uploaded video.');E.bgVideo.addEventListener('loadeddata',sampleWallpaperAccent,{once:true});}else{E.bgImage.src=S.bgObjectUrl;E.bgImage.style.display='block';setBgStatus('Background source: uploaded image.');if(E.bgImage.complete)sampleWallpaperAccent();else E.bgImage.onload=sampleWallpaperAccent;}keepYtOverride();refreshWallpaperAccent();return;}setBgStatus('Invalid background format. Using default.');keepYtOverride();refreshWallpaperAccent();}
function drawClock(){E.clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:!S.appearance.clock24h});}
function setTab(tab){E.tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));E.panels.forEach(p=>p.classList.toggle('active',p.id===`tab-${tab}`));}
function openDrawer(){S.drawerOpen=true;E.drawer.classList.add('open');E.backdrop.classList.add('open');}
function closeDrawer(){S.drawerOpen=false;E.drawer.classList.remove('open');E.backdrop.classList.remove('open');}
function toggleDrawer(){S.drawerOpen?closeDrawer():openDrawer();}
function defaultPos(i){const col=i%3,row=Math.floor(i/3);return{x:col*280,y:row*190};}
function viewportPos(p){const maxX=Math.max(0,window.innerWidth-WIDGET_W),maxY=Math.max(0,window.innerHeight-WIDGET_H);return{x:clamp(Math.round(p.x),0,maxX),y:clamp(Math.round(p.y),0,maxY)};}
function getPos(id,i){const p=S.layout.positions[id];if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))return viewportPos(p);return viewportPos(defaultPos(i));}
function setPos(id,x,y){S.layout.positions[id]=viewportPos({x,y});}
const W={
quickLinks:{title:'Quick Links',render(c,s){const w=document.createElement('div');w.className='links-wrap';(s.links||[]).forEach(l=>{const safeUrl=parseSafeUrl(l&&l.url);if(!safeUrl)return;const safeLabel=(typeof l.label==='string'?l.label.trim():'').slice(0,60)||safeUrl.hostname;const a=document.createElement('a');a.className='pill-link';a.href=safeUrl.href;a.target='_blank';a.rel='noopener noreferrer';a.title=safeLabel;a.setAttribute('aria-label',safeLabel);const i=document.createElement('img');i.src=`${safeUrl.origin}/favicon.ico`;i.alt='';i.width=18;i.height=18;i.loading='lazy';i.referrerPolicy='no-referrer';i.onerror=()=>{i.style.display='none';a.textContent=safeLabel.slice(0,1).toUpperCase();};a.appendChild(i);w.appendChild(a);});c.appendChild(w);},settings(c){const list=document.createElement('div');list.className='stack';const label=document.createElement('input');label.type='text';label.placeholder='Label';const url=document.createElement('input');url.type='url';url.placeholder='https://example.com';const add=document.createElement('button');add.type='button';add.textContent='Add link';add.addEventListener('click',async()=>{const l=(label.value||'').trim().slice(0,60);const safeUrl=parseSafeUrl(url.value);if(!l||!safeUrl)return;S.widgetSettings.quickLinks.links.push({label:l,url:safeUrl.href});label.value='';url.value='';await saveWS();renderWidgets();renderWidgetSettings();});(S.widgetSettings.quickLinks.links||[]).forEach((x,i)=>{const r=document.createElement('div');r.className='link-item';const t=document.createElement('span');t.className='tiny';t.textContent=`${x.label} (${x.url})`;const d=document.createElement('button');d.type='button';d.textContent='Remove';d.addEventListener('click',async()=>{S.widgetSettings.quickLinks.links.splice(i,1);await saveWS();renderWidgets();renderWidgetSettings();});r.append(t,d);list.appendChild(r);});if(!(S.widgetSettings.quickLinks.links||[]).length){const n=document.createElement('div');n.className='tiny';n.textContent='No quick links yet.';list.appendChild(n);}c.append(label,url,add,list);}},
mediaPlayback:{title:'Media Playback',render(c,s){
const wrap=document.createElement('div');wrap.className='media-mini';
const head=document.createElement('div');head.className='media-head';
const source=document.createElement('div');source.className='media-source';
const sourceLogo=document.createElement('img');sourceLogo.alt='';sourceLogo.className='media-source-logo';sourceLogo.loading='lazy';sourceLogo.referrerPolicy='no-referrer';sourceLogo.style.display='none';
const sourceDot=document.createElement('span');sourceDot.className='media-source-dot';
const sourceName=document.createElement('span');sourceName.className='media-source-name';sourceName.textContent='No source';
source.append(sourceLogo,sourceDot,sourceName);
const openBtn=document.createElement('button');openBtn.type='button';openBtn.className='media-open-btn';openBtn.textContent='\u2197';openBtn.disabled=true;
head.append(source,openBtn);
const main=document.createElement('div');main.className='media-main';
const artWrap=document.createElement('div');artWrap.className='media-art';
const art=document.createElement('img');art.alt='Track artwork';art.loading='lazy';art.referrerPolicy='no-referrer';art.style.display='none';
const artFallback=document.createElement('div');artFallback.className='media-art-fallback';artFallback.textContent='No Art';
artWrap.append(art,artFallback);
main.appendChild(artWrap);
const title=document.createElement('div');title.className='media-title';title.textContent='No media playing';
const subtitle=document.createElement('div');subtitle.className='media-subtitle';subtitle.textContent='Play from YouTube Music, Spotify, or Apple Music';
const divider=document.createElement('div');divider.className='media-divider';
const controls=document.createElement('div');controls.className='media-controls';
const prev=document.createElement('button');prev.type='button';prev.className='media-btn';prev.textContent='\u23EE';
const play=document.createElement('button');play.type='button';play.className='media-btn is-primary';play.textContent='\u25B6';
const next=document.createElement('button');next.type='button';next.className='media-btn';next.textContent='\u23ED';
controls.append(prev,play,next);
wrap.append(head,main,title,subtitle,divider,controls);
c.appendChild(wrap);
const refreshSec=clamp(Number(s&&s.refreshSec)||4,2,15);
const setIdle=(msg,sub)=>{sourceName.textContent='No source';sourceLogo.style.display='none';sourceDot.style.display='block';title.textContent=msg;subtitle.textContent=sub||'Play from YouTube Music, Spotify, or Apple Music';art.style.display='none';artFallback.style.display='flex';openBtn.disabled=true;prev.disabled=true;play.disabled=true;next.disabled=true;play.textContent='\u25B6';};
const paint=({tab,snap})=>{const src=sourceFromUrl(tab.url||'');sourceName.textContent=src.name;const logo=tab.favIconUrl||src.logo||'';if(logo){sourceLogo.src=logo;sourceLogo.style.display='block';sourceDot.style.display='none';sourceLogo.onerror=()=>{sourceLogo.style.display='none';sourceDot.style.display='block';};}else{sourceLogo.style.display='none';sourceDot.style.display='block';}title.textContent=(snap.title||tab.title||'Unknown track').slice(0,56);const secondary=[snap.artist,snap.album].filter(Boolean).join(' - ');subtitle.textContent=(secondary||src.name||'Active source').slice(0,72);if(snap.artwork){art.src=snap.artwork;art.style.display='block';artFallback.style.display='none';art.onerror=()=>{art.style.display='none';artFallback.style.display='flex';};}else{art.style.display='none';artFallback.style.display='flex';}openBtn.disabled=false;prev.disabled=false;play.disabled=false;next.disabled=false;play.textContent=snap.playing?'\u275A\u275A':'\u25B6';};
const refresh=async()=>{if(!canUseExtMedia()){setIdle('Media controls unavailable','Reload extension once to grant tab access');return;}const state=await resolveMediaState().catch(()=>null);if(!state){setIdle('Nothing is playing','Start music in any tab');return;}S.media.lastTabId=state.tab.id;paint(state);};
const act=async(kind)=>{if(!Number.isInteger(S.media.lastTabId))return;await sendMediaControl(S.media.lastTabId,kind);setTimeout(refresh,320);};
prev.addEventListener('click',()=>act('prev'));
play.addEventListener('click',()=>act('playpause'));
next.addEventListener('click',()=>act('next'));
openBtn.addEventListener('click',async()=>{if(!canUseExtMedia()||!Number.isInteger(S.media.lastTabId))return;const tabs=await chromeTabsQuery({}).catch(()=>[]);focusTab(tabs.find(t=>t.id===S.media.lastTabId));});
stopMediaPolling();
refresh();
S.media.pollId=setInterval(refresh,refreshSec*1000);
},settings(c){const box=document.createElement('div');box.className='stack';const label=document.createElement('div');label.className='tiny';const slider=document.createElement('input');slider.type='range';slider.min='2';slider.max='15';slider.step='1';slider.value=String(clamp(Number((S.widgetSettings.mediaPlayback&&S.widgetSettings.mediaPlayback.refreshSec)||4),2,15));const paint=()=>{label.textContent=`Auto refresh: ${slider.value}s`;};slider.addEventListener('input',async()=>{if(!S.widgetSettings.mediaPlayback)S.widgetSettings.mediaPlayback={refreshSec:4};S.widgetSettings.mediaPlayback.refreshSec=clamp(+slider.value,2,15);paint();await saveWS();renderWidgets();});paint();box.append(label,slider);c.appendChild(box);}},
todo:{title:'To-do',render(c,s){const u=document.createElement('div');u.className='todo-list';(s.items||[]).slice(0,6).forEach(it=>{const r=document.createElement('div');r.className='tiny';r.textContent=`- ${it}`;u.appendChild(r);});if(!u.childElementCount)u.innerHTML='<div class="tiny">No tasks</div>';c.appendChild(u);},settings(c){const list=document.createElement('div');list.className='stack';const input=document.createElement('input');input.type='text';input.placeholder='Add task';const add=document.createElement('button');add.type='button';add.textContent='Add';add.addEventListener('click',async()=>{const v=input.value.trim();if(!v)return;S.widgetSettings.todo.items.push(v);input.value='';await saveWS();renderWidgets();renderWidgetSettings();});(S.widgetSettings.todo.items||[]).forEach((it,i)=>{const r=document.createElement('div');r.className='todo-item';const t=document.createElement('span');t.className='tiny';t.textContent=it;const d=document.createElement('button');d.type='button';d.textContent='Done';d.addEventListener('click',async()=>{S.widgetSettings.todo.items.splice(i,1);await saveWS();renderWidgets();renderWidgetSettings();});r.append(t,d);list.appendChild(r);});c.append(input,add,list);}},
notes:{title:'Notes',render(c,s){const t=document.createElement('div');t.className='tiny';t.textContent=(s.text||'').slice(0,280)||'Empty note';c.appendChild(t);},settings(c){const a=document.createElement('textarea');a.value=S.widgetSettings.notes.text||'';a.placeholder='Scratchpad';a.addEventListener('input',async()=>{S.widgetSettings.notes.text=a.value;await saveWS();renderWidgets();});c.appendChild(a);}},
calendar:{title:'Calendar',render(c){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),start=first.getDay();const wrap=document.createElement('div');wrap.className='calendar-mini';const head=document.createElement('div');head.className='calendar-head';head.textContent=now.toLocaleString([], {month:'long',year:'numeric'});const week=document.createElement('div');week.className='calendar-week';['S','M','T','W','T','F','S'].forEach(w=>{const el=document.createElement('div');el.textContent=w;week.appendChild(el);});const grid=document.createElement('div');grid.className='calendar-grid';for(let i=0;i<42;i++){const day=document.createElement('div');day.className='calendar-day';let n=0,isCurrent=false;if(i<start){n=prevDays-start+i+1;day.classList.add('is-muted');}else if(i<start+days){n=i-start+1;isCurrent=true;}else{n=i-(start+days)+1;day.classList.add('is-muted');}day.textContent=String(n);if(isCurrent&&n===now.getDate())day.classList.add('is-today');grid.appendChild(day);}wrap.append(head,week,grid);c.appendChild(wrap);},settings(c){const n=document.createElement('div');n.className='tiny';n.textContent='Month preview shown on main page.';c.appendChild(n);}},
pomodoro:{title:'Pomodoro',render(c,s){const p=S.pomo;if(p.remaining<=0){p.mode='work';p.remaining=(s.workMinutes||25)*60;}const tm=document.createElement('div');tm.style.fontSize='1.4rem';tm.style.fontWeight='600';const lb=document.createElement('div');lb.className='tiny';const ctr=document.createElement('div');ctr.className='row-inline';const ss=document.createElement('button');ss.type='button';const rs=document.createElement('button');rs.type='button';rs.textContent='Reset';const paint=()=>{const m=Math.floor(p.remaining/60),sec=p.remaining%60;tm.textContent=`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;lb.textContent=p.mode==='work'?'Focus':'Break';ss.textContent=p.timerId?'Pause':'Start';};const stop=()=>{if(p.timerId){clearInterval(p.timerId);p.timerId=null;}};ss.addEventListener('click',()=>{if(p.timerId){stop();paint();return;}p.timerId=setInterval(()=>{p.remaining-=1;if(p.remaining<=0){p.mode=p.mode==='work'?'break':'work';p.remaining=(p.mode==='work'?s.workMinutes:s.breakMinutes)*60;}paint();},1000);paint();});rs.addEventListener('click',()=>{stop();p.mode='work';p.remaining=(s.workMinutes||25)*60;paint();});ctr.append(ss,rs);c.append(tm,lb,ctr);paint();},settings(c){const w=document.createElement('input');w.type='range';w.min='1';w.max='120';w.value=String(S.widgetSettings.pomodoro.workMinutes);const b=document.createElement('input');b.type='range';b.min='1';b.max='60';b.value=String(S.widgetSettings.pomodoro.breakMinutes);const wl=document.createElement('div');wl.className='tiny';const bl=document.createElement('div');bl.className='tiny';const paint=()=>{wl.textContent=`Work: ${w.value} min`;bl.textContent=`Break: ${b.value} min`;};const sync=async()=>{S.widgetSettings.pomodoro.workMinutes=+w.value;S.widgetSettings.pomodoro.breakMinutes=+b.value;await saveWS();renderWidgets();};w.addEventListener('input',()=>{paint();sync();});b.addEventListener('input',()=>{paint();sync();});c.append(wl,w,bl,b);paint();}},
systemStats:{title:'System Stats',render(c,s){const wrap=document.createElement('div');wrap.className='stats-mini';const add=(label)=>{const row=document.createElement('div');row.className='stat-row';const top=document.createElement('div');top.className='stat-top';const l=document.createElement('span');l.textContent=label;const v=document.createElement('span');v.className='stat-val';v.textContent='--';top.append(l,v);const bar=document.createElement('div');bar.className='stat-bar';const fill=document.createElement('div');fill.className='stat-fill';bar.appendChild(fill);row.append(top,bar);wrap.appendChild(row);return{fill,v};};const set=(m,p,label)=>{const pct=clamp(Number.isFinite(p)?p:0,0,100);m.fill.style.width=`${pct}%`;m.v.textContent=label||`${Math.round(pct)}%`;};const meters={};if(s.showBattery)meters.battery=add('Battery');if(s.showRam)meters.ram=add('RAM');if(s.showCpu)meters.cpu=add('CPU');if(meters.battery){set(meters.battery,0,'n/a');if(navigator.getBattery){navigator.getBattery().then(b=>set(meters.battery,b.level*100,`${Math.round(b.level*100)}%`)).catch(()=>{});}}if(meters.ram){if(performance&&performance.memory&&performance.memory.jsHeapSizeLimit>0){const p=(performance.memory.usedJSHeapSize/performance.memory.jsHeapSizeLimit)*100;set(meters.ram,p,`${Math.round(p)}%`);}else{set(meters.ram,0,'n/a');}}if(meters.cpu){requestAnimationFrame((t1)=>{requestAnimationFrame((t2)=>{const frame=t2-t1;const p=clamp((frame-16.7)*6,0,100);set(meters.cpu,p,`${Math.round(p)}%`);});});}c.appendChild(wrap);},settings(c){const bl=document.createElement('label'),bc=document.createElement('input');bc.type='checkbox';bc.checked=S.widgetSettings.systemStats.showBattery;bl.append(bc,document.createTextNode(' Show battery'));const rl=document.createElement('label'),rc=document.createElement('input');rc.type='checkbox';rc.checked=S.widgetSettings.systemStats.showRam;rl.append(rc,document.createTextNode(' Show RAM'));const cl=document.createElement('label'),cc=document.createElement('input');cc.type='checkbox';cc.checked=S.widgetSettings.systemStats.showCpu;cl.append(cc,document.createTextNode(' Show CPU'));const save=async()=>{S.widgetSettings.systemStats.showBattery=bc.checked;S.widgetSettings.systemStats.showRam=rc.checked;S.widgetSettings.systemStats.showCpu=cc.checked;await saveWS();renderWidgets();};bc.addEventListener('change',save);rc.addEventListener('change',save);cc.addEventListener('change',save);c.append(bl,rl,cl);}}
};
function renderWidgets(){stopMediaPolling();E.widgets.innerHTML='';const ids=S.layout.order.filter(id=>S.layout.enabled[id]);const custom=S.layout.placementMode==='custom';E.widgets.classList.toggle('custom-placement',custom);if(!ids.length)return;ids.forEach((id,i)=>{const d=W[id];if(!d)return;const card=document.createElement('article');card.className='widget-card';card.dataset.widgetId=id;const t=document.createElement('h3');t.className='widget-title';t.textContent=d.title;if(custom)t.style.cursor='move';card.appendChild(t);d.render(card,S.widgetSettings[id]||{});if(custom){const p=viewportPos(getPos(id,i));card.style.left=`${p.x}px`;card.style.top=`${p.y}px`;t.addEventListener('pointerdown',ev=>{if(ev.button!==0)return;ev.preventDefault();const startX=ev.clientX,startY=ev.clientY,start=getPos(id,i);const move=(me)=>{setPos(id,start.x+(me.clientX-startX),start.y+(me.clientY-startY));card.style.left=`${S.layout.positions[id].x}px`;card.style.top=`${S.layout.positions[id].y}px`;};const up=async()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);await saveLayout();renderWidgetSettings();};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);});}E.widgets.appendChild(card);});}
function moveOrder(from,to){const a=[...S.layout.order],i=a.indexOf(from),j=a.indexOf(to);if(i<0||j<0||i===j)return;a.splice(j,0,a.splice(i,1)[0]);S.layout.order=a;}
function renderWidgetList(){E.widgetList.innerHTML='';if(E.placementMode)E.placementMode.value=S.layout.placementMode;const clockRow=document.createElement('div');clockRow.className='widget-row';const clockHead=document.createElement('div');clockHead.className='widget-head';const clockLeft=document.createElement('div');clockLeft.className='row-inline';const clockName=document.createElement('span');clockName.textContent='Clock';const clockFixed=document.createElement('span');clockFixed.className='tiny';clockFixed.textContent='fixed';const clockLabel=document.createElement('label');const clockToggle=document.createElement('input');clockToggle.type='checkbox';clockToggle.checked=!!S.appearance.clockVisible;clockToggle.addEventListener('change',async()=>{S.appearance.clockVisible=clockToggle.checked;applyAppearance();await saveApp();syncAppControls();});clockLabel.append(clockToggle,document.createTextNode(' Enabled'));clockLeft.append(clockName,clockFixed);clockHead.append(clockLeft,clockLabel);clockRow.appendChild(clockHead);E.widgetList.appendChild(clockRow);let dragId=null;S.layout.order.forEach(id=>{const row=document.createElement('div');row.className='widget-row';row.draggable=true;row.dataset.widgetId=id;row.addEventListener('dragstart',()=>{dragId=id;});row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',async e=>{e.preventDefault();if(!dragId||dragId===id)return;moveOrder(dragId,id);await saveLayout();renderWidgetList();renderWidgets();});const h=document.createElement('div');h.className='widget-head';const l=document.createElement('div');l.className='row-inline';const name=document.createElement('span');name.textContent=W[id]?W[id].title:id;const drag=document.createElement('span');drag.className='drag-hint';drag.textContent='drag';const tl=document.createElement('label');const tg=document.createElement('input');tg.type='checkbox';tg.checked=!!S.layout.enabled[id];tg.addEventListener('change',async()=>{S.layout.enabled[id]=tg.checked;await saveLayout();renderWidgets();renderWidgetSettings();});tl.append(tg,document.createTextNode(' Enabled'));l.append(name,drag);h.append(l,tl);row.appendChild(h);E.widgetList.appendChild(row);});}
function renderWidgetSettings(){E.widgetSettings.innerHTML='';const ids=S.layout.order.filter(id=>S.layout.enabled[id]);if(!ids.length){const n=document.createElement('div');n.className='tiny';n.textContent='Enable widgets to edit their settings.';E.widgetSettings.appendChild(n);return;}ids.forEach((id,i)=>{const d=W[id];if(!d)return;const box=document.createElement('div');box.className='widget-row';const t=document.createElement('div');t.className='tiny';t.textContent=d.title;box.appendChild(t);if(S.layout.placementMode==='custom'){const p=getPos(id,i);const row=document.createElement('div');row.className='row-inline';const x=document.createElement('input');x.type='number';x.min='0';x.step='10';x.value=String(p.x);x.style.width='110px';const y=document.createElement('input');y.type='number';y.min='0';y.step='10';y.value=String(p.y);y.style.width='110px';const apply=document.createElement('button');apply.type='button';apply.textContent='Set X/Y';apply.addEventListener('click',async()=>{setPos(id,Number(x.value||0),Number(y.value||0));await saveLayout();renderWidgets();});row.append(document.createTextNode('X'),x,document.createTextNode('Y'),y,apply);box.appendChild(row);}if(typeof d.settings==='function')d.settings(box);E.widgetSettings.appendChild(box);});}
async function hydrate(){const [bg,layout,app,ws]=await Promise.all([dbGet(K.bg),dbGet(K.layout),dbGet(K.appearance),dbGet(K.ws)]);S.layout=normLayout(layout);S.appearance=normApp(app);S.widgetSettings=normWS(ws);S.bgCurrent=normBg(bg);}
function wireTabs(){E.tabs.forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));}
function wireDrawer(){E.settingsToggle.addEventListener('click',toggleDrawer);E.close.addEventListener('click',closeDrawer);E.backdrop.addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key===','){e.preventDefault();toggleDrawer();}if(e.key==='Escape'&&S.drawerOpen){e.preventDefault();closeDrawer();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='l'){e.preventDefault();E.q.focus();E.q.select();}});}
function wireSearch(){E.searchForm.addEventListener('submit',e=>{e.preventDefault();const q=E.q.value.trim();if(!q)return;window.location.assign(`https://www.google.com/search?q=${encodeURIComponent(q)}`);});}
function wireBackground(){
E.bgFile.addEventListener('change',async()=>{const f=E.bgFile.files&&E.bgFile.files[0];if(!f)return;S.bgCurrent={type:'blob',value:f};await saveBg();renderBg();E.bgFile.value='';});
E.bgApply.addEventListener('click',async()=>{const safeUrl=parseSafeUrl(E.bgUrl.value);if(!safeUrl){setBgStatus('Only http/https background URLs are allowed.');return;}S.bgCurrent={type:'url',value:safeUrl.href};await saveBg();renderBg();});
E.bgReset.addEventListener('click',async()=>{S.bgCurrent=null;await saveBg();renderBg();E.bgUrl.value='';});
E.vMuted.addEventListener('change',async()=>{S.appearance.videoMuted=E.vMuted.checked;applyAppearance();await saveApp();syncAppControls();});
E.vPaused.addEventListener('change',async()=>{S.appearance.videoPaused=E.vPaused.checked;applyAppearance();await saveApp();syncAppControls();});
if(E.ytBgToggle){E.ytBgToggle.addEventListener('change',async()=>{if(E.ytBgToggle.checked&&!YT_HTTP_CONTEXT){S.appearance.youtubeBgEnabled=false;E.ytBgToggle.checked=false;await saveApp();syncAppControls();setBgStatus('YouTube background cannot run on extension new-tab pages (Error 153).');hideYouTubeBackground();renderBg();return;}S.appearance.youtubeBgEnabled=E.ytBgToggle.checked;await saveApp();syncAppControls();updateYouTubeBgMode();});}
E.bgDim.addEventListener('input',async()=>{S.appearance.overlayDim=+E.bgDim.value;applyAppearance();await saveApp();syncAppControls();});
E.bgBlur.addEventListener('input',async()=>{S.appearance.glassBlur=+E.bgBlur.value;applyAppearance();await saveApp();syncAppControls();});
}
function wireWidgetTab(){if(E.placementMode){E.placementMode.addEventListener('change',async()=>{S.layout.placementMode=E.placementMode.value==='custom'?'custom':'grid';await saveLayout();renderWidgets();renderWidgetList();renderWidgetSettings();});}if(E.resetPositions){E.resetPositions.addEventListener('click',async()=>{S.layout.positions={};await saveLayout();renderWidgets();renderWidgetSettings();});}E.minimal.addEventListener('click',async()=>{IDS.forEach(id=>S.layout.enabled[id]=false);S.appearance.clockVisible=true;await Promise.all([saveLayout(),saveApp()]);applyAppearance();syncAppControls();renderWidgets();renderWidgetList();renderWidgetSettings();});}
function wireAppearance(){[[E.searchBottom,'searchBottom'],[E.searchWidth,'searchWidth'],[E.glassBlur,'glassBlur'],[E.overlayDim,'overlayDim']].forEach(([input,key])=>{input.addEventListener('input',async()=>{S.appearance[key]=+input.value;applyAppearance();await saveApp();syncAppControls();});});E.clockVisible.addEventListener('change',async()=>{S.appearance.clockVisible=E.clockVisible.checked;applyAppearance();await saveApp();renderWidgetList();});E.clock24h.addEventListener('change',async()=>{S.appearance.clock24h=E.clock24h.checked;drawClock();await saveApp();});}
function downloadJson(name,data){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function wireData(){
E.exportBtn.addEventListener('click',async()=>{const bg=normBg(await dbGet(K.bg));downloadJson('newtab-preferences.json',{exportedAt:new Date().toISOString(),bgCurrent:bg&&bg.type==='url'?bg:{type:'blob',note:'Blob background is local-only and not exported'},layout:S.layout,appearance:S.appearance,widgetSettings:S.widgetSettings});});
E.importInput.addEventListener('change',async()=>{const f=E.importInput.files&&E.importInput.files[0];if(!f)return;try{const j=JSON.parse(await f.text());const hosts=collectImportHosts(j);if(hosts.length){const preview=hosts.slice(0,6).join(', ');const more=hosts.length>6?` (+${hosts.length-6} more)`:'';const ok=window.confirm(`This import contains external URLs from: ${preview}${more}. Continue?`);if(!ok){setBgStatus('Import cancelled.');return;}}if(j.layout){S.layout=normLayout(j.layout);await saveLayout();}if(j.appearance){S.appearance=normApp(j.appearance);await saveApp();}if(j.widgetSettings){S.widgetSettings=normWS(j.widgetSettings);await saveWS();}const cur=normBg(await dbGet(K.bg));const importedBg=normBg(j&&j.bgCurrent);const importedBgWasUrl=!!(j&&j.bgCurrent&&j.bgCurrent.type==='url');if(importedBg){S.bgCurrent=importedBg;await saveBg();}else S.bgCurrent=cur;applyAppearance();syncAppControls();renderBg();updateYouTubeBgMode();renderWidgets();renderWidgetList();renderWidgetSettings();if(importedBgWasUrl&&!importedBg)setBgStatus('Import complete. Unsafe background URL was ignored.');}catch(_){setBgStatus('Failed to import JSON. Check file format.');}finally{E.importInput.value='';}});
E.resetAll.addEventListener('click',async()=>{await dbClear();S.bgCurrent=null;S.layout=structuredClone(DEF_LAYOUT);S.appearance=structuredClone(DEF_APP);S.widgetSettings=structuredClone(DEF_WS);applyAppearance();syncAppControls();renderBg();updateYouTubeBgMode();renderWidgets();renderWidgetList();renderWidgetSettings();});
}
async function init(){wireTabs();wireDrawer();wireSearch();wireBackground();wireWidgetTab();wireAppearance();wireData();await hydrate();applyAppearance();syncAppControls();renderBg();updateYouTubeBgMode();renderWidgets();renderWidgetList();renderWidgetSettings();setTab('background');drawClock();setInterval(drawClock,1000);window.addEventListener('beforeunload',stopMediaPolling,{once:true});window.addEventListener('beforeunload',stopYouTubeBgPolling,{once:true});window.addEventListener('pointerdown',()=>{if(E.bgVideo.style.display!=='none'&&!S.appearance.videoPaused&&E.bgVideo.paused)E.bgVideo.play().catch(()=>{});},{once:true});}
init().catch(()=>setBgStatus('Initialization failed. Check browser IndexedDB support.'));
})();

